Added Soup
edwardslabs/CloudBot pull request #214
Opened 2017-11-10 01:33 UTC by Vault108

Added a soup Command.

2017-11-10 01:44 UTC, linuxdaemon commented on data/food/soup.json
> +" Bowl of Ajiaco ",
The leading space in this string will result in an output of `hands <user> a  Bowl of Ajiaco ` (note the double space before Bowl and the trailing whitespace). I'd recommend removing surrounding whitespace from these strings.
I'd also recommend running the `format_json.py` script from the repository root to reformat the JSON file to follow the standard format for this repository.

2017-11-10 01:49 UTC, linuxdaemon commented on data/food/soup.json
> +" Bowl of Matzah ball soup",
These options would result in `hands <user> a Bowl of Matzah ball soup soup` due to the fact that the template itself adds the word 'soup'

2017-11-11 02:53 UTC, linuxdaemon requested changes

2017-11-11 02:53 UTC, linuxdaemon commented on plugins/foods.py
> +    BasicFood("soup","soup","soup.json","soup"),
There should be a single space following a comma in a parameter list

2017-11-11 02:53 UTC, linuxdaemon commented on data/food/soup.json
> +]
This indentation should be fixed using the `format_json.py` script

2017-11-11 02:53 UTC, linuxdaemon commented on data/food/soup.json
> +"Bowl of Borscht ",
The trailing whitespace here should be removed as well

2017-11-14 22:01 UTC, edwardslabs commented
There are merge conflicts now because I took too long to merge several PRs in. Please fix the merge conflicts.

2017-11-14 23:08 UTC, closed without merging

2017-11-16 01:24 UTC, Vault108 commented
Moved to #220